name: Autumn Reign Poet
favicon: null
layout_spectrum: 0.442568
typography_spectrum: 0.362331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4d0300'
    - '#fefefe'
    - '#f2ab01'
    - '#073ced'
    - '#12f57f'
  brandStrength: 0.75
  lightness: 0.4375
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
