name: Autumn Reign Poet
favicon: null
layout_spectrum: 0.38827
typography_spectrum: 0.96303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#93492e'
    - '#ce7229'
    - '#d3cfac'
    - '#c7aa7f'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
