analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#93492e'
    - '#ce7229'
    - '#d3cfac'
    - '#c7aa7f'
  brandStrength: 0.646959
  lightness: 0.26098
  rhythmicContrast: 0.494088
  saturation: 0
cta: {}
layout_spectrum: 0.665541
name: Autumn Reign - Poet
opengraph: {}
purpose: []
typography_spectrum: 0.733953
