analytics: {}
color:
  brandColors:
    - '#fdfbe4'
    - '#da6e26'
    - '#f5b35d'
    - '#fcdf99'
    - '#7f340c'
  brandStrength: 0.329392
  lightness: 0.291385
  rhythmicContrast: 0.25
  saturation: 0.25
cta: {}
layout_spectrum: 0.74124
name: Autumn Reign Poet
opengraph: {}
purpose: []
typography_spectrum: 0.86311
