name: Autumn Reign Poet
favicon: null
layout_spectrum: 0.88617
typography_spectrum: 0.30022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#881f01'
    - '#ffffff'
    - '#d35e00'
    - '#e11b1c'
    - '#eab274'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
