analytics: {}
color:
  brandColors:
    - '#3B0000'
    - '#A70000'
    - '#9E3B00'
    - '#FBBA00'
    - '#FDEDD0'
  brandStrength: 0.4375
  lightness: 0.375
  rhythmicContrast: 0.75
  saturation: 0.25
cta: {}
layout_spectrum: 0.4933
name: Autumn Reign Poet
opengraph: {}
purpose: []
typography_spectrum: 0.51796
