analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#93492e'
    - '#ce7229'
    - '#d3cfac'
    - '#c7aa7f'
  brandStrength: 0.726351
  lightness: 0.568412
  rhythmicContrast: 0.842905
  saturation: 0.317568
cta: {}
layout_spectrum: 0.665541
name: Autumn Reign - Poet
opengraph: {}
purpose: []
typography_spectrum: 0.733953
