name: Autumn Reign Poet
favicon: null
layout_spectrum: 0.442568
typography_spectrum: 0.362331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#881f01'
    - '#ffffff'
    - '#d35e00'
    - '#e11b1c'
    - '#eab274'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
