analytics: {}
color:
  brandColors:
    - '#000000'
    - '#481000'
    - '#000000'
    - '#D88808'
    - '#F0E090'
  brandStrength: 0.329392
  lightness: 0.291385
  rhythmicContrast: 0.25
  saturation: 0.25
cta: {}
layout_spectrum: 0.507601
name: Autumn Reign Poet
opengraph: {}
purpose: []
typography_spectrum: 0.741554
