analytics: {}
color:
  brandColors:
    - '#881f01'
    - '#ffffff'
    - '#d35e00'
    - '#e11b1c'
    - '#eab274'
  brandStrength: 0.368243
  lightness: 0.181588
  rhythmicContrast: 0.5
  saturation: 0.165541
cta: {}
layout_spectrum: 0.442568
name: Autumn Reign Poet
opengraph: {}
purpose: []
typography_spectrum: 0.362331
