name: Autumn Reign
favicon: null
layout_spectrum: 0.24956
typography_spectrum: 0.41112
title: TRUTH SERUM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f47320'
    - '#0a0905'
    - '#5c2e09'
    - '#974b0f'
    - '#584429'
  brandStrength: 0.6939070576336235
  lightness: 0.7061176400166005
  saturation: 0.046079789754003286
  rhythmicContrast: 0.9661007921677083
purpose: []
