name: Autumn Reign Poet
favicon: null
layout_spectrum: 0.74255
typography_spectrum: 0.08831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e0000'
    - '#a98555'
    - '#543614'
    - '#dbb787'
    - '#f0e5c4'
  brandStrength: 0.375
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
