name: Autumn Reign Poet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.94295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#1a0000'
    - '#ffd200'
    - '#ff4a00'
    - '#fdfcf7'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
