analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#93492e'
    - '#ce7229'
    - '#d3cfac'
    - '#c7aa7f'
  brandStrength: 0.5
  lightness: 0.541385
  rhythmicContrast: 0.628378
  saturation: 0.460304
cta: {}
layout_spectrum: 0.665541
name: Autumn Reign - Poet
opengraph: {}
purpose: []
typography_spectrum: 0.733953
