name: Autumn Reign Poet
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11302
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfbe4'
    - '#da6e26'
    - '#f5b35d'
    - '#fcdf99'
    - '#7f340c'
  brandStrength: 0.5625
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0.75
purpose: []
